### PR TITLE
fix: unknown download state after switching tabs

### LINKED ISSUE #155: [BUG] Undefined behaviour when switching to other tab while installing addon
**Installer Version**
`master`

**Describe the bug**
Switching to another tab while installing an addon currently results in undefined behaviour, with the main button turning to "Install" even though the download was not finished. It is not clear if the download and / or install finishes or not.

**To Reproduce**
1. Start installing A32NX
2. Switch to the Settings tab
3. Switch back to the A32NX tab

**Expected behavior**
* Behavior is remains consistent and clear

Discord username (if different from GitHub): someperson#4953

### PR DESCRIPTION
**Pull request by FoxtrotSierra6829**
Fixes #155 

## Summary of Changes
- Move [selectedTrack, installedTrack, installStatus] to Redux
- general fixes and improvements

## Additional context

Known issues:
- install status in menu bar not changing while app is open (old)
- wrong install status after install/update for very short time (->0,3s) after tabs switched
- [completed!] only visible for very short (if at all) after install/update -> compromise due to current structure

Discord username (if different from GitHub):
Foxtrot Sierra#6420

### CODE REVIEW

File: src/renderer/components/AircraftSection/index.tsx [hunk 1]
```diff
@@ -39,18 +39,28 @@ import { Track, Tracks } from "renderer/components/AircraftSection/TrackSelector
...
 const settings = new Store;
 
 const { Paragraph } = Typography;
 
 type Props = {
-    mod: Mod
+    mod: Mod,
+}
+
+type propTypes = {
```
Comment (nistei) [inline src/renderer/components/AircraftSection/index.tsx:52]:
```suggestion
type AircraftSectionProps = {
```

File: src/renderer/components/AircraftSection/index.tsx [hunk 2]
```diff
@@ -70,7 +80,7 @@ enum MsfsStatus {
     Checking,
 }
 
-const index: React.FC<Props> = (props: Props) => {
+const index: React.FC<Props> = (props: propTypes) => {
```
Comment (nistei) [inline src/renderer/components/AircraftSection/index.tsx:83]:
```suggestion
const index: React.FC<Props> = (props: AircraftSectionProps) => {
```

File: src/renderer/components/AircraftSection/index.tsx [hunk 3]
```diff
@@ -39,18 +39,28 @@ import { Track, Tracks } from "renderer/components/AircraftSection/TrackSelector
 import { install, needsUpdate, getCurrentInstall } from "@flybywiresim/fragmenter";
 import * as path from 'path';
 import os from 'os';
+import store from '../../redux/store';
 
 const settings = new Store;
 
 const { Paragraph } = Typography;
 
 type Props = {
```
Comment (nistei) [inline src/renderer/components/AircraftSection/index.tsx:48]:
```suggestion
```

File: src/renderer/components/AircraftSection/index.tsx [hunk 4]
```diff
@@ -39,18 +39,28 @@ import { Track, Tracks } from "renderer/components/AircraftSection/TrackSelector
...
-    mod: Mod
+    mod: Mod,
+}
```
Comment (nistei) [inline src/renderer/components/AircraftSection/index.tsx:50]:
```suggestion
```

**Review by nistei — CHANGES_REQUESTED** [review]

File: src/renderer/components/AircraftSection/index.tsx (hunk 4 above)
Comment (ZigTag) [reply src/renderer/components/AircraftSection/index.tsx:51]: It should be on a newline

File: src/renderer/components/AircraftSection/index.tsx [hunk 5]
```diff
@@ -39,18 +39,28 @@ import { Track, Tracks } from "renderer/components/AircraftSection/TrackSelector
...
 import os from 'os';
+import store from '../../redux/store';
 
 const settings = new Store;
 
 const { Paragraph } = Typography;
 
-type Props = {
-    mod: Mod
+//props coming from renderer/components/App
```
Comment (Benjozork) [inline src/renderer/components/AircraftSection/index.tsx:48]:
```suggestion
// Props coming from renderer/components/App
```

File: src/renderer/components/AircraftSection/index.tsx [hunk 6]
```diff
@@ -39,18 +39,28 @@ import { Track, Tracks } from "renderer/components/AircraftSection/TrackSelector
...
+type TransferredProps = {
+    mod: Mod,
+}
+
+//all props
```
Comment (Benjozork) [inline src/renderer/components/AircraftSection/index.tsx:53]:
```suggestion
// All props
```

File: src/renderer/components/AircraftSection/index.tsx [hunk 7]
```diff
@@ -86,25 +96,43 @@ const index: React.FC<Props> = (props: Props) => {
...
+    // TODO: Switch to Redux when variants are available
     const [selectedVariant] = useState<ModVariant>(props.mod.variants[0]);
-    const [selectedTrack, setSelectedTrack] = useState<ModTrack>();
-    const [installedTrack, setInstalledTrack] = useState<ModTrack>();
 
-    const [installStatus, setInstallStatus] = useState<InstallStatus>(InstallStatus.Unknown);
+    const installedTrack = props.installedtrack;
+    const setInstalledTrack = (new_installed_track: ModTrack) => {
+        store.dispatch({ type: 'INSTALLED_TRACK', payload: new_installed_track });
+    };
```
Comment (Benjozork) [inline src/renderer/components/AircraftSection/index.tsx:126]:
```suggestion
    };
    
```

File: src/renderer/components/AircraftSection/index.tsx [hunk 8]
```diff
@@ -127,12 +155,17 @@ const index: React.FC<Props> = (props: Props) => {
     useEffect(() => {
         const checkMsfsInterval = setInterval(checkIfMSFS, 500);
 
-        return () => clearInterval(checkMsfsInterval);
```
Comment (Benjozork) [inline src/renderer/components/AircraftSection/index.tsx:130]: Why?

File: src/renderer/components/AircraftSection/index.tsx [hunk 9]
```diff
@@ -458,4 +505,12 @@ const index: React.FC<Props> = (props: Props) => {
     );
 };
 
-export default index;
+//Defining the state types raises errors with mod: Mod in /App/index
```
Comment (Benjozork) [inline src/renderer/components/AircraftSection/index.tsx:508]:
```suggestion
// Defining the state types raises errors with mod: Mod in /App/index
```

File: src/renderer/components/ChangelogModal/index.tsx [hunk 10]
```diff
@@ -7,7 +7,10 @@ import ReactHtmlParser from 'react-html-parser';
 // @ts-ignore: Disabling ts check here because this package has no @types
 import changelog from '../../../../.github/CHANGELOG.md';
 
-function showchangelog(props: any) {
+type ChangelogProps = {
+    showchangelog: boolean
+}
+const showchangelog: React.FC<null> = (props: ChangelogProps) => {
```
Comment (Benjozork) [inline src/renderer/components/ChangelogModal/index.tsx:13]:
```suggestion

const showchangelog: React.FC<ChangelogProps> = (props: ChangelogProps) => {
```

File: src/renderer/redux/actionTypes/index.ts [hunk 11]
```diff
@@ -2,3 +2,7 @@ export const UPDATE_DOWNLOAD_PROGRESS = 'updateDownLoadProgress';
 export const REGISTER_NEW_DOWNLOAD = 'registerNewDownload';
 export const DELETE_DOWNLOAD = 'deleteDownload';
 export const CALL_WARNING_MODAL = 'callWarningModal';
+export const UPDATE_INSTALL_STATE = 'UPDATE_INSTALL_STATE';
+export const CHANGELOG = 'CHANGELOG';
```
Comment (Benjozork) [inline src/renderer/redux/actionTypes/index.ts:6]: I would give this a more descriptive name. What does it actually do ?

File: src/renderer/redux/actionTypes/index.ts [hunk 12]
```diff
@@ -2,3 +2,7 @@ export const UPDATE_DOWNLOAD_PROGRESS = 'updateDownLoadProgress';
...
+export const SELECT_TRACK = 'SELECT_TRACK';
+export const INSTALLED_TRACK = 'INSTALLED_TRACK';
```
Comment (Benjozork) [inline src/renderer/redux/actionTypes/index.ts:8]: Same for this one.

**Review by Benjozork — CHANGES_REQUESTED** [review]

File: src/renderer/components/AircraftSection/index.tsx (hunk 8 above)
Comment (FoxtrotSierra6829) [reply src/renderer/components/AircraftSection/index.tsx:130]: Oh yeah that was me trying to do something and forgot to revert it completely, because it wasn't obviously changing the code XD

**Review by Benjozork — APPROVED** [review]
LGTM
